### ISSUE TITLE
imsitu import error

### ISSUE THREAD

**Issue by yunsujeon** [aai4r/aai4r-Situation-Recognition#1]
ggnn.py 를 실행하는 도중 
import imsitu를 실행하지 못하고 멈추는 에러가 발생했습니다.

Traceback (most recent call last):
  File "ggnn.py", line 74, in <module>
    from baseline_crf import BaselineCRF
  File "/root/share/aai4r-Situation-Recognition/baseline_crf.py", line 14, in <module>
    from imsitu import imSituVerbRoleLocalNounEncoder
ModuleNotFoundError: No module named 'imsitu'

따라서 https://github.com/my89/imSitu 에서 imsitu.py 를 본 결과 사용하는 클래스가 같아
이를 다운받아 패키지에 넣어주었는데 동작에는 관계가 없는지 궁금합니다.

**Comment by YoNyeoSeok** [comment]
네 baseline_crf.py 및 imsitu.py 의 경우 해당 레포지토리의 코드와 동일합니다.
