### ISSUE TITLE
torch.save시 path문제

### ISSUE THREAD

**Issue by yunsujeon** [aai4r/aai4r-Situation-Recognition#3]
training하는 중 epoch 를 한번 반복하기도 전에

FileNotFoundError: [Errno 2] No such file or directory: 'models/resnet101_v4.1_crf_rmsprop_lr1e-03_T_4/gnn_model_three_anotation_test0pth.tar'
에러가 발생했습니다.

따라서 models 폴더와 resnet101~~_03_T_4 폴더를 만들어주었고 training간 데이터는 이 안에 쌓이게 됐는데요

모델을 바꾸거나 다른 변경사항이 있을 시 항상 폴더를 이와같이 만들어줘야하나요?

**Comment by YoNyeoSeok** [comment]
네 현재 코드 상에서는 폴더가 만들어져 있는 것을 가정하여 진행합니다.
다양한 모델 및 환경에서 실험을 진행하려면, 편의를 위해 자동으로 폴더를 만들어주는 코드를 넣어 진행하면 되겠습니다.
